### ISSUE TITLE
Does this work with the current version of Yank? Ligand resname error.

### ISSUE THREAD

**Issue by jeffcomer** [choderalab/mhc#3]
I'm able to run other Yank examples (t4-lysozyme), but for this example I get an error that has something to do with the ligand resname. It appears to be trying to open the ligand as a mol2 file, but it's a peptide in PDB format. I am also running into the same error when I try to modify the t4-lysozyme example to use a peptide ligand.

2020-01-28 09:44:23,673: Setting CUDA platform to use precision model 'mixed'.
2020-01-28 09:44:23,772: WARNING - openmmtools.multistate.multistatesampler - Warning: The openmmtools.multistate API is experimental and may change in future releases
2020-01-28 09:44:23,813: Setting up the systems for mhc and peptide using solvent pme
Traceback (most recent call last):
  File "run_yank.py", line 150, in <module>
    main(args.yaml_script_path, args.job_id, args.n_jobs)
  File "run_yank.py", line 138, in main
    experiment_builder.run_experiments()
  File "/home/comer/anaconda3/envs/yank/lib/python3.7/site-packages/yank/experiment.py", line 751, in run_experiments
    completed[exp_index] = self._run_experiment(exp, write_status=write_status)
  File "/home/comer/anaconda3/envs/yank/lib/python3.7/site-packages/yank/experiment.py", line 3247, in _run_experiment
    built_experiment = self._build_experiment(experiment_path, experiment)
  File "run_yank.py", line 126, in _build_experiment
    experiment = super(TwoRestraintsBuilder, self)._build_experiment(*args, **kwargs)
  File "/home/comer/anaconda3/envs/yank/lib/python3.7/site-packages/yank/experiment.py", line 3042, in _build_experiment
    ligand_resname = utils.Mol2File(ligand_descr['filepath']).resname
  File "/home/comer/anaconda3/envs/yank/lib/python3.7/site-packages/yank/utils.py", line 1124, in resname
    return next(self.resnames)
StopIteration

**Comment by andrrizzi** [comment]
Hi @jeffcomer . I don't think this will work with YANK. The automatic pipeline doesn't support peptide ligands. You might be able to run with YANK if you setup the system separately (see [the docs](http://getyank.org/latest/yamlpages/systems.html#arbitrary-phase-free-energies-setup-by-user)).

**Comment by jeffcomer** [comment]
Thanks! I’ll try that.
